name: warung_sayur
description: Aplikasi warung sayur offline-first (HPP, penjualan, laporan, hutang)
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.19.0
  collection: ^1.18.0

  flutter_riverpod: ^2.5.1

  hive: ^2.2.3
  hive_flutter: ^1.1.0

  path_provider: ^2.1.4
  share_plus: ^10.0.2
  file_picker: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
